// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserNewRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserNewRequest) Reset()         { *m = UserNewRequest{} }
func (m *UserNewRequest) String() string { return proto.CompactTextString(m) }
func (*UserNewRequest) ProtoMessage()    {}
func (*UserNewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{1}
}

func (m *UserNewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserNewRequest.Unmarshal(m, b)
}
func (m *UserNewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserNewRequest.Marshal(b, m, deterministic)
}
func (m *UserNewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserNewRequest.Merge(m, src)
}
func (m *UserNewRequest) XXX_Size() int {
	return xxx_messageInfo_UserNewRequest.Size(m)
}
func (m *UserNewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserNewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserNewRequest proto.InternalMessageInfo

func (m *UserNewRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserNewResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserNewResponse) Reset()         { *m = UserNewResponse{} }
func (m *UserNewResponse) String() string { return proto.CompactTextString(m) }
func (*UserNewResponse) ProtoMessage()    {}
func (*UserNewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{2}
}

func (m *UserNewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserNewResponse.Unmarshal(m, b)
}
func (m *UserNewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserNewResponse.Marshal(b, m, deterministic)
}
func (m *UserNewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserNewResponse.Merge(m, src)
}
func (m *UserNewResponse) XXX_Size() int {
	return xxx_messageInfo_UserNewResponse.Size(m)
}
func (m *UserNewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserNewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserNewResponse proto.InternalMessageInfo

func (m *UserNewResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserNewResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UsersAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersAllRequest) Reset()         { *m = UsersAllRequest{} }
func (m *UsersAllRequest) String() string { return proto.CompactTextString(m) }
func (*UsersAllRequest) ProtoMessage()    {}
func (*UsersAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{3}
}

func (m *UsersAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersAllRequest.Unmarshal(m, b)
}
func (m *UsersAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersAllRequest.Marshal(b, m, deterministic)
}
func (m *UsersAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersAllRequest.Merge(m, src)
}
func (m *UsersAllRequest) XXX_Size() int {
	return xxx_messageInfo_UsersAllRequest.Size(m)
}
func (m *UsersAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersAllRequest proto.InternalMessageInfo

type UsersAllResponse struct {
	Data                 []*User  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersAllResponse) Reset()         { *m = UsersAllResponse{} }
func (m *UsersAllResponse) String() string { return proto.CompactTextString(m) }
func (*UsersAllResponse) ProtoMessage()    {}
func (*UsersAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{4}
}

func (m *UsersAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersAllResponse.Unmarshal(m, b)
}
func (m *UsersAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersAllResponse.Marshal(b, m, deterministic)
}
func (m *UsersAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersAllResponse.Merge(m, src)
}
func (m *UsersAllResponse) XXX_Size() int {
	return xxx_messageInfo_UsersAllResponse.Size(m)
}
func (m *UsersAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersAllResponse proto.InternalMessageInfo

func (m *UsersAllResponse) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UsersAllResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*UserNewRequest)(nil), "UserNewRequest")
	proto.RegisterType((*UserNewResponse)(nil), "UserNewResponse")
	proto.RegisterType((*UsersAllRequest)(nil), "UsersAllRequest")
	proto.RegisterType((*UsersAllResponse)(nil), "UsersAllResponse")
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor_d570e3e37e5899c5) }

var fileDescriptor_d570e3e37e5899c5 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x03, 0x33, 0x95, 0xb4, 0xb8, 0x58, 0x42, 0x8b, 0x53,
	0x8b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0xc0, 0x6c, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0xa6,
	0xcc, 0x14, 0x25, 0x15, 0x2e, 0x3e, 0x90, 0x5a, 0xbf, 0xd4, 0xf2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4,
	0xe2, 0x12, 0x6c, 0xba, 0x94, 0x9c, 0xb8, 0xf8, 0xe1, 0xaa, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53,
	0x85, 0x24, 0xb9, 0x58, 0x52, 0x12, 0x4b, 0x12, 0xc1, 0xca, 0xb8, 0x8d, 0x58, 0xf5, 0x40, 0xf2,
	0x41, 0x60, 0x21, 0x21, 0x11, 0x2e, 0xd6, 0xd4, 0xa2, 0xa2, 0xfc, 0x22, 0xb0, 0x35, 0x9c, 0x41,
	0x10, 0x8e, 0x92, 0x20, 0xc4, 0x8c, 0x62, 0xc7, 0x9c, 0x1c, 0xa8, 0x55, 0x4a, 0xce, 0x5c, 0x02,
	0x08, 0x21, 0x0c, 0x73, 0x99, 0x89, 0x32, 0x37, 0x89, 0x0d, 0xec, 0x69, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xa7, 0x29, 0x78, 0x5b, 0x08, 0x01, 0x00, 0x00,
}
